### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by deennoo** [moroen/ikea-tradfri#2]
Hello, 

Thanks for your great work and sharing it.

I want to add my Tradfri solution to Domoticz using virtual switch as a python plugin isn't already available.

reading your Readme, it's looks like i have to put Gateway IP and Key on a config file.

Please can you share an exemple of this config file ?

**Comment by moroen** [comment]
If you run the script from the command-line, you can specify the IP and key with the --gateway and --key parameters. This is only needed once, after that the key and ip will be read from the ini-file...

**Comment by deennoo** [comment]
Ok Perfect thank you !

Maybe you can add on your git an exemple of tradfi.ini file to be more explicite

Did you plan ti provied a python plugin for Domoticz ?

**Comment by moroen** [comment]
I'll expand the readme a bit. The tradfri.py script has been put on the back burner for a while, as I focus on developing a Python plugin instead! Having a bit of trouble with the plugin though, so it might be worth it to use the script in the meantime...

**Comment by deennoo** [comment]
if you want a beta tester i can i have a full dev setup, on rpi and on a x86 64b vm

**Comment by moroen** [comment]
Thanks! I'll continue work on the plugin, but in the meantime, I have updated the python-script to use the latest pytradfri API.
