### ISSUE TITLE
Unable to create config file

### ISSUE THREAD

**Issue by ghost** [moroen/ikea-tradfri#3]
Thanks for the script,
I have some trouble creating a config file using your example:
`python3 tradfri.py --gateway 192.168.1.144 --key mysecretkey`                                                                                                                                                                     

`usage: tradfri.py [-h]
                  {config,on,off,list,showhex,level,whitetemp,hex,rgb} ...
tradfri.py: error: argument command: invalid choice: '192.168.1.144' (choose from 'config', 'on', 'off', 'list', 'showhex', 'level', 'whitetemp', 'hex', 'rgb')`

`python3 tradfri.py --gateway 192.168.1.144 --key mysecretkey list`                                                                                                                                                                

`usage: tradfri.py [-h]
                  {config,on,off,list,showhex,level,whitetemp,hex,rgb} ...
tradfri.py: error: argument command: invalid choice: '192.168.1.144' (choose from 'config', 'on', 'off', 'list', 'showhex', 'level', 'whitetemp', 'hex', 'rgb')
`
I've also tried this:
`python3 tradfri.py config 192.168.1.144 mysecretkey`

But that gives me:
`Traceback (most recent call last):
  File "./tradfri.py", line 99, in <module>
    hostConfig=GetConfig(args)
  File "./tradfri.py", line 28, in GetConfig
    psk = api_factory.generate_psk(args.KEY)
  File "/home/user/.local/lib/python3.7/site-packages/pytradfri/api/libcoap_api.py", line 164, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/home/user/.local/lib/python3.7/site-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File "/home/user/.local/lib/python3.7/site-packages/pytradfri/api/libcoap_api.py", line 85, in _execute
    raise RequestTimeout() from None
pytradfri.error.RequestTimeout
`
Thanks

**Comment by moroen** [comment]
This is a work in progress, and the readme is hopelessly out of date. The config is created using the config command:
`
./tradfri.py config IP KEY
`

I've updated the readme to reflect this change.

Regards,
M
